scholar-system:
  build: .
  command: npm run startdev
  environment:
    NODE_ENV: development
  ports:
    - '3000:3000'
  volumes:
    - .:/home/node/scholar-system
    - /home/node/scholar-system/node_modules